switch over to clang, drop gcc entirely

diff --git a/build b/build
--- a/build
+++ b/build
@@ -8,8 +8,9 @@ usage()
 {
     echo "
 Commands: 
-    debug         - build all.
-    test [libdir] - build all & run gTest for specified library.
+    all           - Build all with Debug flag.
+    test [libdir] - Build all & run gTest for specified library.
+    clean         - Deletes build directory.
 
         [libdir]  - one of the directories in lib/
     "
@@ -19,6 +20,34 @@ if [ -z "${1+x}" ]; then
     usage
     exit 1
 fi
+
+clean()
+{
+    rm -rf $build_dir
+}
+
+make_all()
+{
+    echo ">> Building all with debug flags <<"
+    cmake -G Ninja -S . -B "${build_dir}"
+    cmake --build "${build_dir}" -- all
+}
+
+run_test()
+{
+    if [ -n "${1-}" ]; then
+        if [ ! -d "${lib_dir}/$1" ]; then
+            echo "=> ERROR: Library directory $1 does not exist in ${lib_dir}/ <="
+            usage
+            exit 1
+        fi
+        echo ">> Run $1 Test <<"
+        "${build_dir}/tests/$1"
+    else
+        usage
+        exit 1
+    fi
+}
 
 update_vscode_configs()
 {
@@ -37,39 +66,18 @@ for p in ['.vscode/launch.json', '.vscode/tasks.json']:
 "
 }
 
-make_all()
-{
-    update_vscode_configs
-    echo ">> Building all with debug flags <<"
-    # Clear the CMake cache file if it exists to ensure a clean configure
-    rm -f "${build_dir}/CMakeCache.txt"
-    cmake -G Ninja -S . -B "${build_dir}"
-    cmake --build "${build_dir}" -- all
-}
-
-run_test()
-{
-    if [ -n "${1-}" ]; then
-        if [ ! -d "${lib_dir}/$1" ]; then
-            echo "=> ERROR: Library directory $1 does not exist in ${lib_dir}/ <="
-            usage
-            exit 1
-        fi
-        make_all
-        echo ">> Run $1 Test <<"
-        "${build_dir}/bin/$1"
-    else
-        usage
-        exit 1
-    fi
-}
-
 case "$1" in
-    "debug")
+    "all")
+        update_vscode_configs
         make_all
         ;;
     "test")
+        update_vscode_configs
+        make_all
         run_test "${2-}"
+        ;;
+    "clean")
+        clean
         ;;
     *)
         usage
